### ISSUE TITLE
Error while executing `yarn build`

### ISSUE THREAD

**Issue by SteversIO** [ProjectOpenSea/seadrop#42]
Following instructions exactly.
- `git clone --recurse-submodules https://github.com/ProjectOpenSea/seadrop && cd seadrop`  **[success]**
- `yarn install` **[success]**
- `yarn build` | failed with error below.

```
Generating typings for: 36 artifacts in dir: typechain-types for target: ethers-v5
An unexpected error occurred:

TypeError: Cannot convert a Symbol value to a string
    at Array.join (<anonymous>)
    at GlobSync._process (<root>\seadrop\node_modules\typechain\node_modules\glob\sync.js:113:53)
    at new GlobSync (<root>\seadrop\node_modules\typechain\node_modules\glob\sync.js:46:10)
    at globSync (<root>\seadrop\node_modules\typechain\node_modules\glob\sync.js:24:10)
    at <root>\seadrop\node_modules\typechain\src\utils\glob.ts:6:13
    at Array.map (<anonymous>)
    at glob (<root>\seadrop\node_modules\typechain\src\utils\glob.ts:5:35)
    at SimpleTaskDefinition.action (<root>\seadrop\node_modules\@typechain\hardhat\src\index.ts:69:26)
    at Environment._runTaskDefinition (<root>\seadrop\node_modules\hardhat\src\internal\core\runtime-environment.ts:308:35)
    at Environment.run (<root>\seadrop\node_modules\hardhat\src\internal\core\runtime-environment.ts:156:25)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by lifeisgooddev** [comment]
Same problem for me as well.
`TypeError: Cannot convert a Symbol value to a string`

**Comment by SteversIO** [comment]
For WIndows users, I recommend simply using WSL (Windows Subsystem for Linux).  I could not reproduce these issues in any Linux/Unix environment.

1. Install/Update WSL
2. Install NVM & Set Version to 16
3. Make sure you have your SSH key added to the SSH agent (so `--recurse-submodules` will work)
4. Go through README in this project.
